-- Table for teaching assignments (multi-department/license support)
CREATE TABLE IF NOT EXISTS public.teacher_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id UUID REFERENCES auth.users(id) NOT NULL,
    department_id INTEGER REFERENCES public.departments(id),
    niveau TEXT, -- L1, L2, L3, M1, M2 or NULL for "all"
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.teacher_assignments ENABLE ROW LEVEL SECURITY;

-- Policies
DO $$ BEGIN
    CREATE POLICY "Admins can do everything on teacher_assignments" ON public.teacher_assignments
        FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'Administrateur');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE POLICY "Teachers can view their own assignments" ON public.teacher_assignments
        FOR SELECT USING (auth.uid() = teacher_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Grant access
GRANT ALL ON TABLE public.teacher_assignments TO authenticated;
GRANT ALL ON TABLE public.teacher_assignments TO service_role;
