-- Create announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Académique', 'Administratif', 'Vie Étudiante', 'Toutes')),
    priority TEXT NOT NULL DEFAULT 'Moyenne' CHECK (priority IN ('Basse', 'Moyenne', 'Haute', 'Urgente')),
    author TEXT NOT NULL DEFAULT 'Administration',
    is_pinned BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add user_id column if it doesn't exist
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'announcements' 
        AND column_name = 'user_id'
    ) THEN
        ALTER TABLE public.announcements ADD COLUMN user_id UUID REFERENCES auth.users(id);
    END IF;
END $$;

-- Add priority column if it doesn't exist
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'announcements' 
        AND column_name = 'priority'
    ) THEN
        ALTER TABLE public.announcements ADD COLUMN priority TEXT NOT NULL DEFAULT 'Moyenne' CHECK (priority IN ('Basse', 'Moyenne', 'Haute', 'Urgente'));
    END IF;
END $$;

-- Add is_pinned column if it doesn't exist
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'announcements' 
        AND column_name = 'is_pinned'
    ) THEN
        ALTER TABLE public.announcements ADD COLUMN is_pinned BOOLEAN DEFAULT false;
    END IF;
END $$;

-- Enable RLS
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- Policies

-- Everyone can view announcements
DO $$ BEGIN
    CREATE POLICY "Public announcements are viewable by everyone" ON public.announcements
        FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Only Admins and Teachers can insert announcements
DO $$ BEGIN
    DROP POLICY IF EXISTS "Authenticated users can insert announcements" ON public.announcements;
    CREATE POLICY "Teachers and Admins can insert announcements" ON public.announcements
        FOR INSERT WITH CHECK (
            public.get_user_role() IN ('Enseignant', 'Administrateur')
        );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Only authors or admins can update/delete
DO $$ BEGIN
    CREATE POLICY "Users can update their own announcements" ON public.announcements
        FOR UPDATE USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE POLICY "Users can delete their own announcements" ON public.announcements
        FOR DELETE USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Grant access
GRANT ALL ON TABLE public.announcements TO authenticated;
GRANT ALL ON TABLE public.announcements TO service_role;

-- Insert sample data
INSERT INTO public.announcements (title, content, category, priority, author, is_pinned)
VALUES 
('Bienvenue sur CampusConnect', 'Découvrez toutes les fonctionnalités de votre nouvelle application universitaire.', 'Administratif', 'Haute', 'Direction', true),
('Conférence sur l''IA', 'Une conférence sur l''intelligence artificielle aura lieu ce jeudi en amphithéâtre B.', 'Académique', 'Moyenne', 'Dept. Informatique', false)
ON CONFLICT DO NOTHING;

