-- Create filieres table
CREATE TABLE IF NOT EXISTS public.filieres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    department_id BIGINT REFERENCES public.departments(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.filieres ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone (public data)
CREATE POLICY "Enable read access for all users" ON public.filieres
    FOR SELECT USING (true);

-- Allow write access to service role only (or admins via app logic)
-- For now, read-only for public.

-- Insert some sample data if needed (optional)
-- INSERT INTO public.filieres (nom, department_id) VALUES ('Informatique', 1);
